# Welcome To The World Of Jupyter

<img style="float: left;"  src="images/city.png"  width="30%">

# 04-01. Jupyter Shortcuts And Basic Python

## Jupyter shortcuts

<code>↑</code> / <code>↓</code> to move, <code>enter</code> to edit

<code>Esc</code> to exit edit mode

<code>Shift</code> + <code>enter</code> to run code

<code>a</code> / <code>b</code> to add cell above/below

<code>d</code>  <code>d</code> to delete cell

<code>1</code> / <code>2</code> / <code>3</code>... to add comment

press <code>h</code> for more shortcuts

## Basic Practice

### Learn the basic function you need to know.

## 1. Basic Shortcut In Jupyter

In [1]:
#Use arrow button to move up and down

In [2]:
#Use Ctrl+Enter or Shift+Enter at this block to run it.

print("Hello Juypter")

Hello Juypter


In [3]:
#Use dd to delete this block.

print("Delete Me")

Delete Me


In [4]:
#Use B to create a new block Below.

#Then trying to wirte something in it. (like Print function.)

In [5]:
print("Hello")

Hello


## 2. Basic Math Calculate & Print

In [6]:
#Remember to import these head file

import numpy  as  np
import scipy  as  sp
import cv2

from matplotlib import pyplot as plt
plt.rcParams['figure.figsize'] = (10, 10)        # large images
plt.rcParams['image.interpolation'] = 'nearest'  # don't interpolate: show square pixels

In [7]:
#This is how variable work in Python.

a = 2

b = 3

c = a + b

print(c)

# Compile this block to see waht will happened.

5


## 3. Data Type

In [8]:
a = 2.5
b = 3
c = "012"
print type(a),type(b),type(c)

#compare the difference

print "c + str(a) =", c+str(a), type(c+str(a))

print "int(c) + a = ", int(c)+a, type(int(c)+a)

<type 'float'> <type 'int'> <type 'str'>
c + str(a) = 0122.5 <type 'str'>
int(c) + a =  14.5 <type 'float'>


## 4. If Else

In [9]:
#This is how "if" work in Python. and print out "true".
#Below is code I use the variable last block to print out true.

if a == 2 :
    if c == 6 :             # <- If this line is true,         
        print("true")       # <- do this. 
    else :                  # <- Otherwise,
        print("false")      # <- do this. 

# Compile this block to see waht will happened.

## 5. For Loop

In [10]:
#This is how "For" work in Python.
#Below is code how you can print the word "nine" nine time.

for i in range(1,7,2) :     # <- You can asign the range (a,b) by yourself, and it will run from a to b-1 
    for j in range(3):    # <- or just make it run from 0 to x-1                
        print ("nine "+"i="+str(i)+" j="+str(j))  # <- You can use + to combine string

# Compile this block to see waht will happened.   

nine i=1 j=0
nine i=1 j=1
nine i=1 j=2
nine i=3 j=0
nine i=3 j=1
nine i=3 j=2
nine i=5 j=0
nine i=5 j=1
nine i=5 j=2


## 6. 2D Array

In [11]:
#This is how matrix work in Python.
#(don't change row after print a line, and print out variabe with other texts)

x = np.ones([3,3])
y = np.zeros([4,4])

print(x.shape)
print(x)
print("\n")
print(y.shape)
print(y)

z = y
z[ 1:3 , 1:3 ] = 5 # Assign numbers in matrix's range. 
print(z)

# Compile this block to see waht will happened. 

(3, 3)
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


(4, 4)
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.  0.  0.  0.]
 [ 0.  5.  5.  0.]
 [ 0.  5.  5.  0.]
 [ 0.  0.  0.  0.]]


## 7. Input

In [12]:
# This is how you can get input frome the keyboard.

temp = input("input:")

print(temp)

# Compile this block to see waht will happened. 

input:


SyntaxError: unexpected EOF while parsing (<string>, line 0)

##  8. slice notation & advance print
#### Use [m:n] to choose index from m to n-1
#### # index of array
| p | y | t | h | o | n |
|---|---|---|---|---|---|
| 0 | 1 | 2 | 3 | 4 | 5 |
|-5 |-4 |-3 |-2 |-1 | X |

In [14]:
x = np.arange(0, 10 ,1)

print "x[:]=",
print x[:]

print "x[:-1]=%s" %(x[:-1])

print ("x[2:]=%s" %(x[2:]))

print "x[2:-3]={0}\nx[2:7]={1}".format(x[2:-3], x[2:7])

x[:]= [0 1 2 3 4 5 6 7 8 9]
x[:-1]=[0 1 2 3 4 5 6 7 8]
x[2:]=[2 3 4 5 6 7 8 9]
x[2:-3]=[2 3 4 5 6]
x[2:7]=[2 3 4 5 6]


## Basic Chanllenge

#### Now with the knowledge above, trying to finish these task.

## 1. Multiplication Table

In [15]:
#  Now, try to print a multiplication table (from 1~9) with for function

#  It should look like this 

#  1*1=1 1*2=2 ...
#  2*1=2 2*2=4 ...
#  ...

In [16]:
# Finish your code here #

## 2. Matrix

In [17]:
#Now, try to create a 2d array with 1 on the border and 0 inside.

# It should look like this 

#        1  1  1  1
#        1  0  0  1
#        1  0  0  1
#        1  1  1  1


In [18]:
# Finish your code here #

##  3. Draw z = cos( x^2 + y^2 ) 

In [23]:
#  Hint : We have done draw z = sin(x^2 + y^2)/(x^2 + y^2), just modify the code!
#         review chapter "example for function evaluation" in "04-01-01-python-tutorial"

In [24]:
#Step:
    #1. import numpy & matplotlib.pyplot
    #2. meshgrid the x, y
    #3. use the result of meshgrid to draw

## Congraduation !  You have finished this lab !

# Advance Chanllenge
#### If you have some extra time, maybe you can try the chanllenge below.

## 4.  Matrix With Input

In [21]:
#Now, try to combine "input", "array", "if", and "for"
#to create a 2d array with input (int) and output like this

# input 4

# 1 1 1 1
# 1 0 0 1
# 1 0 0 1
# 1 1 1 1

# input 7

# 1 1 1 1 1 1 1 
# 1 0 0 0 0 0 1
# 1 0 1 1 1 0 1
# 1 0 1 0 1 0 1
# 1 0 1 1 1 0 1
# 1 0 0 0 0 0 1
# 1 1 1 1 1 1 1

In [22]:
# Finish your code here #